# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa6574b924b74f7cb5a8b5fe3efaa3156058339f5eb631868694df14660afe3c9bdd6ec37ade82ec1038858f38635cf9d24ed1ad49ff94d475166ec90cb9d56c

test:
  secret_key_base: 8213d79d544ef1d1705f02fba7092de4f3090f749f61a7a8a5fce29a13e5a18d427aad3838d17f33f6d34a2d4a6a9f0f42e5a71077ede01c47debf482693a545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
